### ISSUE TITLE
Game board with tiles

### ISSUE THREAD

**Issue by morgan-rog** [morgan-rog/Wumpus-World#1]
Create a  4x4 game board with tile objects.

**Comment by morgan-rog** [comment]
Struggling with how to generate random tiles with one Wumpus, one gold.
* How to check if there is already a tile with a Wumpus or gold
* How many pits will be generated?

**Comment by MichaelEssmyer** [comment]
You have created a gameboard with tiles :)
Now move on to the robot class... remember, abstractly this classes functionality is more like an interface than an object. For development of the robot class I would first treat it like a test class...
