### ISSUE TITLE
Robot -> Tiles

### ISSUE THREAD

**Issue by morgan-rog** [morgan-rog/Wumpus-World#2]
Create robot that is able to move from tile to tile on the game board.

**Comment by MichaelEssmyer** [comment]
From looking it over and with no testing everything seems setup except one thing... how do you display the robot in a tile on the board? This leads me wonder what the user interface (UI) looks like too??

**Comment by morgan-rog** [comment]
I set up the robot to be a tilde ~ on the board. I made it a tile type.

**Comment by MichaelEssmyer** [comment]
Good thinking, that completes this issue
